# specify docker-compose version
version: '2'

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: angular-client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forwarding

  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229 #bound to debugging outlet attached to local Node from Docker
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 server.js
    # links:
    #   - mongodb # link this service to the database service

  mongodb: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding